#!/bin/bash

# ssup - upload screenshot

set -x # Show commands as they are run.
set -e # Exit on error.

# Generate random file name for image.
IMAGE_NAME=$(head -c 40 /dev/urandom | base64 | perl -pe 's~\W~~g' | head -c 20)

## CHANGE THE LINE BELOW to reflect the URL that the uploaded file will appear at:
URL="http://www.your.server.com/img/$IMAGE_NAME.png"

# Make sure a file with this name doesn't already exist.
# Shouldn't happen with the length of random name we're using.
if curl --head "$URL" | head -1 | grep "200 OK" >/dev/null; then
  exit 1
fi

FILE_TO_UPLOAD="/tmp/${IMAGE_NAME}.png"

# Copy image from clipboard to temp directory.
pngpaste "$FILE_TO_UPLOAD"

## CHANGE THE LINE BELOW to use the upload command of your choice.
scp "$FILE_TO_UPLOAD" your.server.com:/www/img/

# Copy URL to clipboard.
echo -n "$URL" | pbcopy

say "image uploaded"
